# -*- coding: utf-8 -*-
"""Sales_Data_Analysis_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhi4aguAltO5SOAFnzOJ2OK6pMmm2fC3
"""

import pandas as pd
import matplotlib.pyplot as plt

print("Sales Data Analysis Project")
print("Setup completed successfully!")

data = {
    "Date": [
        "2025-01-10", "2025-01-20",
        "2025-02-05", "2025-02-18",
        "2025-03-10", "2025-03-25",
        "2025-04-08", "2025-04-22",
        "2025-05-12", "2025-05-28",
        "2025-06-10", "2025-06-25"
    ],

    "Category": [
        "Electronics", "Clothing",
        "Electronics", "Furniture",
        "Clothing", "Electronics",
        "Furniture", "Clothing",
        "Electronics", "Furniture",
        "Clothing", "Electronics"
    ],

    "Sales": [
        12000, 8000,
        15000, 10000,
        9000, 18000,
        13000, 11000,
        20000, 14000,
        12500, 22000
    ]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"])

df

# Monthly sales
monthly_sales = df.groupby(
    df["Date"].dt.to_period("M")
)["Sales"].sum()

# Quarterly sales
quarterly_sales = df.groupby(
    df["Date"].dt.to_period("Q")
)["Sales"].sum()

# Category-wise sales
category_sales = df.groupby("Category")["Sales"].sum()

print("MONTHLY SALES")
print(monthly_sales)

print("\nQUARTERLY SALES")
print(quarterly_sales)

print("\nCATEGORY-WISE SALES")
print(category_sales)

plt.figure(figsize=(10, 5))

plt.plot(df["Date"], df["Sales"], marker="o")

plt.title("Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))

plt.bar(
    monthly_sales.index.astype(str),
    monthly_sales.values
)

plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))

plt.bar(
    category_sales.index,
    category_sales.values
)

plt.title("Category-wise Sales")
plt.xlabel("Category")
plt.ylabel("Total Sales")

plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 7))

plt.pie(
    category_sales.values,
    labels=category_sales.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Sales Share by Category")
plt.tight_layout()
plt.show()

# 1. Save Sales Over Time
plt.figure(figsize=(10, 5))
plt.plot(df["Date"], df["Sales"], marker="o")
plt.title("Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.savefig("sales_over_time.png")
plt.show()


# 2. Save Monthly Sales
plt.figure(figsize=(10, 5))
plt.bar(monthly_sales.index.astype(str), monthly_sales.values)
plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("monthly_sales.png")
plt.show()


# 3. Save Category-wise Sales
plt.figure(figsize=(8, 5))
plt.bar(category_sales.index, category_sales.values)
plt.title("Category-wise Sales")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.savefig("category_sales.png")
plt.show()


# 4. Save Sales Share
plt.figure(figsize=(7, 7))
plt.pie(
    category_sales.values,
    labels=category_sales.index,
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Sales Share by Category")
plt.tight_layout()
plt.savefig("sales_share.png")
plt.show()

print("All 4 charts saved successfully!")